// Data analyst (level 4), ST0118 v1.1. The KSB wording (`detail`) is copied from the
// official standard published by IfATE / Skills England:
//   https://skillsengland.education.gov.uk/apprenticeships/st0118-v1-1
// Titles and keywords are Canopy's own short labels for display and suggestion matching.

import type { Standard } from '../../../../shared/types';
import { k } from './ksb';

export const DATA_ANALYST: Standard = {
  id: 'st0118-v1-1',
  name: 'Data analyst (level 4)',
  reference: 'ST0118 v1.1',
  sourceUrl:
    'https://skillsengland.education.gov.uk/apprenticeships/st0118-v1-1',
  ksbs: [
    k(
      'K1',
      'K',
      'Legislation for the safe use of data',
      ['legislation', 'law', 'gdpr', 'data protection', 'legal'],
      'current relevant legislation and its application to the safe use of data',
    ),
    k(
      'K2',
      'K',
      'Data and information security policies',
      ['security', 'policy', 'procedure', 'access', 'information security'],
      'organisational data and information security standards, policies and procedures relevant to data management activities',
    ),
    k(
      'K3',
      'K',
      'Data life cycle and routine analysis',
      ['data life cycle', 'lifecycle', 'analysis', 'routine'],
      'principles of the data life cycle and the steps involved in carrying out routine data analysis tasks',
    ),
    k(
      'K4',
      'K',
      'Open, public, administrative and research data',
      ['open data', 'public data', 'research data', 'administrative data'],
      'principles of data, including open and public data, administrative data, and research data',
    ),
    k(
      'K5',
      'K',
      'Structured vs unstructured data',
      ['structured', 'unstructured', 'text', 'csv', 'json'],
      'the differences between structured and unstructured data',
    ),
    k(
      'K6',
      'K',
      'Data structures and database design',
      ['database', 'schema', 'table', 'sql', 'data model'],
      'the fundamentals of data structures, database system design, implementation and maintenance',
    ),
    k(
      'K7',
      'K',
      'User experience and domain context',
      ['user experience', 'ux', 'domain', 'context', 'user'],
      'principles of user experience and domain context for data analytics',
    ),
    k(
      'K8',
      'K',
      'Data quality risks and mitigations',
      [
        'data quality',
        'quality',
        'missing',
        'duplicate',
        'validation',
        'cleanse',
      ],
      'quality risks inherent in data and how to mitigate or resolve these',
    ),
    k(
      'K9',
      'K',
      'Defining customer requirements',
      ['requirements', 'customer', 'stakeholder', 'brief', 'scope'],
      'principal approaches to defining customer requirements for data analysis',
    ),
    k(
      'K10',
      'K',
      'Combining data from different sources',
      ['combine', 'join', 'merge', 'sources', 'integration'],
      'approaches to combining data from different sources',
    ),
    k(
      'K11',
      'K',
      'Organisational tools and methods',
      ['tool', 'excel', 'power bi', 'tableau', 'python', 'sql'],
      'approaches to organisational tools and methods for data analysis',
    ),
    k(
      'K12',
      'K',
      'Organisational data architecture',
      ['architecture', 'data warehouse', 'pipeline', 'data lake'],
      'organisational data architecture',
    ),
    k(
      'K13',
      'K',
      'Statistics for analysing datasets',
      [
        'statistics',
        'statistical',
        'mean',
        'median',
        'regression',
        'distribution',
      ],
      'principles of statistics for analysing datasets',
    ),
    k(
      'K14',
      'K',
      'Descriptive, predictive, prescriptive analytics',
      ['descriptive', 'predictive', 'prescriptive', 'analytics', 'forecast'],
      'the principles of descriptive, predictive and prescriptive analytics',
    ),
    k(
      'K15',
      'K',
      'Ethics of using and collating data',
      ['ethics', 'ethical', 'bias', 'privacy', 'consent'],
      'the ethical aspects associated with the use and collation of data',
    ),
    k(
      'S1',
      'S',
      'Use data systems securely (Privacy by Design)',
      ['secure', 'security', 'privacy', 'privacy by design', 'access'],
      'Use data systems securely to meet requirements and in line with organisational procedures and legislation including principles of Privacy by Design',
    ),
    k(
      'S2',
      'S',
      'Implement the data analysis lifecycle',
      ['analysis', 'lifecycle', 'collect', 'clean', 'analyse', 'report'],
      'implement the stages of the data analysis lifecycle',
    ),
    k(
      'S3',
      'S',
      'Apply data classification',
      ['classification', 'classify', 'category', 'sensitive'],
      'apply principles of data classification within data analysis activity',
    ),
    k(
      'S4',
      'S',
      'Analyse data sets and structures',
      ['analyse', 'dataset', 'data set', 'query', 'sql'],
      'analyse data sets taking account of different data structures and database designs',
    ),
    k(
      'S5',
      'S',
      'Assess user experience and domain context',
      ['user experience', 'ux', 'domain', 'context', 'user'],
      'assess the impact on user experience and domain context on data analysis activity',
    ),
    k(
      'S6',
      'S',
      'Identify and escalate data quality risks',
      ['data quality', 'escalate', 'risk', 'issue', 'mitigation'],
      'identify and escalate quality risks in data analysis with suggested mitigation or resolutions as appropriate',
    ),
    k(
      'S7',
      'S',
      'Customer requirements analysis',
      ['requirements', 'customer', 'stakeholder', 'brief'],
      'undertake customer requirements analysis and implement findings in data analytics planning and outputs',
    ),
    k(
      'S8',
      'S',
      'Identify data sources and combination risks',
      ['data source', 'sources', 'combine', 'join', 'merge'],
      'identify data sources and the risks and challenges to combination within data analysis activity',
    ),
    k(
      'S9',
      'S',
      'Apply data architecture requirements',
      ['architecture', 'data warehouse', 'pipeline', 'standards'],
      'apply organizational architecture requirements to data analysis activities',
    ),
    k(
      'S10',
      'S',
      'Apply statistical methods',
      ['statistics', 'statistical', 'regression', 'hypothesis', 'significance'],
      'apply statistical methodologies to data analysis tasks',
    ),
    k(
      'S11',
      'S',
      'Apply predictive analytics',
      ['predictive', 'prediction', 'forecast', 'model', 'machine learning'],
      'apply predictive analytics in the collation and use of data',
    ),
    k(
      'S12',
      'S',
      'Collaborate and communicate with stakeholders',
      [
        'stakeholder',
        'communicate',
        'present',
        'presentation',
        'meeting',
        'collaborate',
      ],
      'collaborate and communicate with a range of internal and external stakeholders using appropriate styles and behaviours to suit the audience',
    ),
    k(
      'S13',
      'S',
      'Data mining, forecasting and modelling',
      [
        'data mining',
        'time series',
        'forecast',
        'modelling',
        'trend',
        'pattern',
      ],
      'use a range of analytical techniques such as data mining, time series forecasting and modelling techniques to identify and predict trends and patterns in data',
    ),
    k(
      'S14',
      'S',
      'Turn data into reports and dashboards',
      ['dashboard', 'report', 'chart', 'graph', 'infographic', 'visualisation'],
      'collate and interpret qualitative and quantitative data and convert into infographics, reports, tables, dashboards and graphs',
    ),
    k(
      'S15',
      'S',
      'Select the right data tools',
      ['tool', 'excel', 'power bi', 'tableau', 'python', 'sql'],
      'select and apply the most appropriate data tools to achieve the optimum outcome',
    ),
    k(
      'B1',
      'B',
      'Productive, professional, secure environment',
      ['professional', 'secure', 'organised', 'productive'],
      'maintain a productive, professional and secure working environment',
    ),
    k(
      'B2',
      'B',
      'Shows initiative and resourcefulness',
      ['initiative', 'resourceful', 'proactive', 'problem'],
      'show initiative, being resourceful when faced with a problem and taking responsibility for solving problems within their own remit',
    ),
    k(
      'B3',
      'B',
      'Works independently and collaboratively',
      ['independent', 'team', 'collaborate', 'colleague', 'pair'],
      'work independently and collaboratively',
    ),
    k(
      'B4',
      'B',
      'Logical and analytical',
      ['logical', 'analytical', 'reasoning', 'analyse'],
      'logical and analytical',
    ),
    k(
      'B5',
      'B',
      'Finds root causes and solves problems',
      ['root cause', 'problem', 'issue', 'investigate', 'fix'],
      'identify issues quickly, investigating and solving complex problems and applying appropriate solutions. Ensures the true root cause of any problem is found and a solution is identified which prevents recurrence.',
    ),
    k(
      'B6',
      'B',
      'Resilient, learns from failure',
      ['resilient', 'resilience', 'challenge', 'setback', 'failure', 'mistake'],
      'resilient - viewing obstacles as challenges and learning from failure.',
    ),
    k(
      'B7',
      'B',
      'Adaptable to change',
      ['adapt', 'adaptable', 'change', 'flexible', 'pivot'],
      'adaptable to changing contexts within the scope of a project, direction of the organisation or Data Analyst role.',
    ),
  ],
};
