// Software developer (level 4), ST0116 v1.2. The KSB wording (`detail`) is copied from the
// official standard published by IfATE / Skills England:
//   https://skillsengland.education.gov.uk/apprenticeships/st0116-v1-2
// Titles and keywords are Canopy's own short labels for display and suggestion matching.

import type { Standard } from '../../../../shared/types';
import { k } from './ksb';

export const SOFTWARE_DEVELOPER: Standard = {
  id: 'st0116-v1-2',
  name: 'Software developer (level 4)',
  reference: 'ST0116 v1.2',
  sourceUrl:
    'https://skillsengland.education.gov.uk/apprenticeships/st0116-v1-2',
  ksbs: [
    k(
      'K1',
      'K',
      'Software development life-cycle',
      ['lifecycle', 'life-cycle', 'sdlc', 'requirements', 'design', 'release'],
      'all stages of the software development life-cycle (what each stage contains, including the inputs and outputs)',
    ),
    k(
      'K2',
      'K',
      'Roles in the development lifecycle',
      ['role', 'responsibility', 'product owner', 'tester', 'developer'],
      'roles and responsibilities within the software development lifecycle (who is responsible for what)',
    ),
    k(
      'K3',
      'K',
      'Project life-cycle and my role',
      ['project', 'milestone', 'my role', 'organisation'],
      'the roles and responsibilities of the project life-cycle within your organisation, and your role',
    ),
    k(
      'K4',
      'K',
      'Communicating with different audiences',
      ['communicate', 'audience', 'email', 'slack', 'presentation'],
      'how best to communicate using the different communication methods and how to adapt appropriately to different audiences',
    ),
    k(
      'K5',
      'K',
      'Development methodologies (agile, waterfall)',
      ['agile', 'waterfall', 'scrum', 'kanban', 'sprint', 'methodology'],
      'the similarities and differences between different software development methodologies, such as agile and waterfall.',
    ),
    k(
      'K6',
      'K',
      'How software teams work effectively',
      ['team', 'teamwork', 'stand-up', 'standup', 'retro', 'retrospective'],
      'how teams work effectively to produce software and how to contribute appropriately',
    ),
    k(
      'K7',
      'K',
      'Design approaches and patterns',
      ['pattern', 'design pattern', 'architecture', 'reusable'],
      'software design approaches and patterns, to identify reusable solutions to commonly occurring problems',
    ),
    k(
      'K8',
      'K',
      'Organisational policies and procedures',
      ['policy', 'procedure', 'gdpr', 'compliance', 'data protection'],
      'organisational policies and procedures relating to the tasks being undertaken, and when to follow them. For example the storage and treatment of GDPR sensitive data.',
    ),
    k(
      'K9',
      'K',
      'Algorithms, logic and data structures',
      [
        'algorithm',
        'data structure',
        'array',
        'queue',
        'tree',
        'sorting',
        'search',
        'hash',
      ],
      'algorithms, logic and data structures relevant to software development for example: arrays, stacks, queues, linked lists, trees, graphs, hash tables, sorting algorithms, searching algorithms, critical sections and race conditions',
    ),
    k(
      'K10',
      'K',
      'Relational and non-relational databases',
      ['database', 'sql', 'nosql', 'query', 'schema', 'table'],
      'principles and uses of relational and non-relational databases',
    ),
    k(
      'K11',
      'K',
      'Software designs and specifications',
      [
        'specification',
        'spec',
        'design doc',
        'technical design',
        'requirements',
      ],
      'software designs and functional or technical specifications',
    ),
    k(
      'K12',
      'K',
      'Testing frameworks and methodologies',
      ['testing', 'test framework', 'tdd', 'jest', 'pytest', 'junit'],
      'software testing frameworks and methodologies',
    ),
    k(
      'S1',
      'S',
      'Create logical, maintainable code',
      [
        'code',
        'coding',
        'refactor',
        'clean code',
        'maintainable',
        'programming',
      ],
      'create logical and maintainable code',
    ),
    k(
      'S2',
      'S',
      'Develop effective user interfaces',
      ['ui', 'user interface', 'frontend', 'front-end', 'css', 'layout', 'ux'],
      'develop effective user interfaces',
    ),
    k(
      'S3',
      'S',
      'Link code to data sets',
      ['data', 'dataset', 'api', 'database', 'json', 'integration'],
      'link code to data sets',
    ),
    k(
      'S4',
      'S',
      'Unit test code and fix errors',
      ['unit test', 'unit testing', 'test', 'bug', 'fix', 'error'],
      'test code and analyse results to correct errors found using unit testing',
    ),
    k(
      'S5',
      'S',
      'Run a range of test types',
      [
        'integration test',
        'system test',
        'uat',
        'performance',
        'security testing',
        'load test',
      ],
      'conduct a range of test types, such as Integration, System, User Acceptance, Non-Functional, Performance and Security testing.',
    ),
    k(
      'S6',
      'S',
      'Identify and create test scenarios',
      ['test case', 'test scenario', 'edge case', 'test plan'],
      'identify and create test scenarios',
    ),
    k(
      'S7',
      'S',
      'Problem solving and debugging',
      ['debug', 'debugging', 'problem', 'issue', 'root cause', 'troubleshoot'],
      'apply structured techniques to problem solving, debug code and understand the structure of programmes in order to identify and resolve issues',
    ),
    k(
      'S8',
      'S',
      'Create simple software designs',
      ['diagram', 'design', 'uml', 'flowchart', 'sketch'],
      'create simple software designs to effectively communicate understanding of the program',
    ),
    k(
      'S9',
      'S',
      'Create use cases and user stories',
      [
        'user story',
        'user stories',
        'use case',
        'acceptance criteria',
        'backlog',
      ],
      'create analysis artefacts, such as use cases and/or user stories',
    ),
    k(
      'S10',
      'S',
      'Build, manage and deploy code',
      ['deploy', 'deployment', 'build', 'pipeline', 'release', 'environment'],
      'build, manage and deploy code into the relevant environment',
    ),
    k(
      'S11',
      'S',
      'Apply a suitable development approach',
      ['object oriented', 'oop', 'event driven', 'procedural', 'paradigm'],
      'apply an appropriate software development approach according to the relevant paradigm (for example object oriented, event driven or procedural)',
    ),
    k(
      'S12',
      'S',
      'Follow designs and specifications',
      ['specification', 'spec', 'design', 'requirements'],
      'follow software designs and functional or technical specifications',
    ),
    k(
      'S13',
      'S',
      'Follow testing frameworks and methods',
      ['testing', 'test framework', 'test plan', 'qa'],
      'follow testing frameworks and methodologies',
    ),
    k(
      'S14',
      'S',
      'Continuous integration and source control',
      [
        'git',
        'github',
        'version control',
        'ci',
        'pull request',
        'merge',
        'code review',
      ],
      'follow company, team or client approaches to continuous integration, version and source control',
    ),
    k(
      'S15',
      'S',
      'Communicate solutions to any audience',
      ['present', 'presentation', 'demo', 'explain', 'stakeholder'],
      'communicate software solutions and ideas to technical and non-technical stakeholders',
    ),
    k(
      'S16',
      'S',
      'Apply algorithms and data structures',
      ['algorithm', 'data structure', 'optimise', 'complexity'],
      'apply algorithms, logic and data structures',
    ),
    k(
      'S17',
      'S',
      'Implement designs securely and maintainably',
      ['security', 'secure', 'maintainable', 'vulnerability', 'implement'],
      'interpret and implement a given design whist remaining compliant with security and maintainability requirements',
    ),
    k(
      'B1',
      'B',
      'Works independently and takes responsibility',
      [
        'independent',
        'independently',
        'ownership',
        'responsibility',
        'motivated',
      ],
      'Works independently and takes responsibility. For example, has a disciplined and responsible approach to risk and stays motivated and committed when facing challenges',
    ),
    k(
      'B2',
      'B',
      'Applies logical thinking',
      ['logical', 'reasoning', 'decision', 'analyse'],
      'Applies logical thinking. For example, uses clear and valid reasoning when making decisions related to undertaking work instructions',
    ),
    k(
      'B3',
      'B',
      'Productive, professional, secure environment',
      ['professional', 'secure', 'organised', 'productive', 'workspace'],
      'Maintains a productive, professional and secure working environment',
    ),
    k(
      'B4',
      'B',
      'Works collaboratively and inclusively',
      [
        'team',
        'collaborate',
        'pair',
        'mentor',
        'colleague',
        'inclusion',
        'diversity',
      ],
      'Works collaboratively with a wide range of people in different roles, internally and externally, with a positive attitude to inclusion & diversity',
    ),
    k(
      'B5',
      'B',
      'Acts with integrity (ethics, law, data)',
      ['ethics', 'ethical', 'integrity', 'gdpr', 'personal data', 'legal'],
      'Acts with integrity with respect to ethical, legal and regulatory ensuring the protection of personal data, safety and security.',
    ),
    k(
      'B6',
      'B',
      'Shows initiative solving problems',
      ['initiative', 'resourceful', 'problem', 'proactive'],
      'Shows initiative and takes responsibility for solving problems within their own remit, being resourceful when faced with a problem to solve.',
    ),
    k(
      'B7',
      'B',
      'Communicates effectively',
      ['communicate', 'explain', 'present', 'presentation', 'feedback'],
      'Communicates effectively in a variety of situations to both a technical and non-technical audience.',
    ),
    k(
      'B8',
      'B',
      'Curious about the business context',
      ['curious', 'curiosity', 'business', 'customer', 'improve', 'explore'],
      'Shows curiosity to the business context in which the solution will be used, displaying an inquisitive approach to solving the problem. This includes the curiosity to explore new opportunities, techniques and the tenacity to improve methods and maximise performance of the solution and creativity in their approach to solutions.',
    ),
    k(
      'B9',
      'B',
      'Continued professional development',
      [
        'cpd',
        'course',
        'workshop',
        'lecture',
        'learning',
        'certification',
        'conference',
      ],
      'Committed to continued professional development.',
    ),
  ],
};
